version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:16.1
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:latest
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080" 
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  prometheus-ifood:
    container_name: prometheus_ifood
    image: prometheus-ifood
    network_mode: "host"